/*flexberryautogenerated="true"*/
namespace IIS.calendar
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class EventL : BaseListForm<Event>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public EventL() : base(Event.Views.EventL)
        {
            EditPage = EventE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Event/EventL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
