<%--flexberryautogenerated="false"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="EventE.aspx.cs" Inherits="IIS.calendar.EventE" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>
<%-- Autogenerated section start [Register] --%>
<%-- Autogenerated section end [Register] --%>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="<%= Constants.FormCssClass %> <%= Constants.EditFormCssClass %>">
        <h2 class="<%= Constants.FormHeaderCssClass %> <%= Constants.EditFormHeaderCssClass %>">Редактирование события</h2>
        <div class="<%= Constants.FormToolbarCssClass %> <%= Constants.EditFormToolbarCssClass %> <%= Constants.StickyCssClass %>">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="<%= Constants.FormControlsCssClass %> <%= Constants.EditFormControlsCssClass %>">
            <%-- Autogenerated section start [Controls] --%>
<!-- autogenerated start -->
<div>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlNameLabel" runat="server" Text="Название" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlName" runat="server">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlNameValidator" runat="server" ControlToValidate="ctrlName"
ErrorMessage="Не указано: Name" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlPlaceLabel" runat="server" Text="Место" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlPlace" runat="server">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlPlaceValidator" runat="server" ControlToValidate="ctrlPlace"
ErrorMessage="Не указано: Place" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlTypeLabel" runat="server" Text="Тип" EnableViewState="False">
</asp:Label>
<asp:DropDownList ID="ctrlType" CssClass="descTxt" runat="server" >
<asp:ListItem>Задача</asp:ListItem>
<asp:ListItem>Встреча</asp:ListItem>
<asp:ListItem>Рабочее совещание</asp:ListItem>
</asp:DropDownList>



<asp:RequiredFieldValidator ID="ctrlTypeValidator" runat="server" ControlToValidate="ctrlType"
ErrorMessage="Не указано: Type" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlRepeatTypeLabel" runat="server" Text="Варианты повторения" EnableViewState="False">
</asp:Label>
 
<asp:DropDownList ID="ctrlRepeatType" CssClass="descTxt" runat="server" OnSelectedIndexChanged="ctrlRepeatType_SelectedIndexChanged()" >
	<asp:ListItem>Не повторять</asp:ListItem>
<asp:ListItem>Ежедневно</asp:ListItem>
<asp:ListItem>Еженедельно</asp:ListItem>
<asp:ListItem>Ежемесячно</asp:ListItem>
<asp:ListItem>Ежегодно</asp:ListItem>
</asp:DropDownList>
</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlStartDateLabel" runat="server" Text="Начало события" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlStartDate" runat="server"/>
</div>
<asp:RequiredFieldValidator ID="ctrlStartDateValidator" runat="server" ControlToValidate="ctrlStartDate"
ErrorMessage="Не указано: StartDate" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlEndDateLabel" runat="server" Text="Окончание события" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlEndDate" runat="server"/>
</div>
<asp:RequiredFieldValidator ID="ctrlEndDateValidator" runat="server" ControlToValidate="ctrlEndDate"
ErrorMessage="Не указано: EndDate" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div id="VS" runat="server" style="display:none;">
    <div class="clearfix">
  <asp:Label CssClass="descLbl" ID="RepeatStartDateLabel" runat="server" Text="Начало повторения" EnableViewState="False" >
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="RepeatStartDate" runat="server"/>
</div>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="RepeatEndDateLabel" runat="server" Text="Окончание повторения" EnableViewState="False" >
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="RepeatEndDate" runat="server" />
</div>
    </div>
</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlCommentLabel" runat="server" Text="Комментарий" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlComment" runat="server">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlCommentValidator" runat="server" ControlToValidate="ctrlComment"
ErrorMessage="Не указано: Comment" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<asp:ScriptManager ID="ScriptManager1" runat="server" >
</asp:ScriptManager>

<div style="clear: left">
	<ac:AjaxGroupEdit ID="ctrlMember" runat="server" ReadOnly="false" />

</div>
<br/>

</div>
<!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder0" runat="server">
     <script src="/Scripts/jquery-1.12.4.js" type="text/javascript"></script>
<%--    <script type="text/javascript">
        $(document).ready(function () {
            $('<%= ctrlRepeatType.ClientID %>').change(function () {
                $('<%= VS.ClientID %>').show();
                })
        })
    </script>--%>
    <script type="text/javascript">
        $document.ready(function () {
            //ctrlRepeatType_SelectedIndexChanged(function()
            //{
                document.getElementById('<%= VS.ClientID %>').style.display="inline";
            //})
        })
    </script>
</asp:Content>
