//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.calendar
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Event.
    /// </summary>
    // *** Start programmer edit section *** (Event CustomAttributes)

    // *** End programmer edit section *** (Event CustomAttributes)
    [AutoAltered()]
    [Caption("Событие")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("EventE", new string[] {
            "Name as \'Название\'",
            "Place as \'Место\'",
            "Type as \'Тип\'",
            "StartDate as \'Начало события\'",
            "EndDate as \'Окончание события\'",
            "Comment as \'Комментарий\'"})]
    [AssociatedDetailViewAttribute("EventE", "Member", "MemberE", true, "", "Участники", true, new string[] {
            ""})]
    [View("EventL", new string[] {
            "Name as \'Название\'",
            "Place as \'Место\'",
            "Type as \'Тип\'",
            "StartDate as \'Дата начала\'",
            "EndDate as \'Дата окончания\'",
            "Comment as \'Комментарий\'"})]
    public class Event : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fPlace;
        
        private string fType;
        
        
        private System.DateTime fStartDate;
        
        private System.DateTime fEndDate;
        
        private string fComment;
        
        private IIS.calendar.DetailArrayOfMember fMember;
        
        // *** Start programmer edit section *** (Event CustomMembers)

        // *** End programmer edit section *** (Event CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Event.Name CustomAttributes)

        // *** End programmer edit section *** (Event.Name CustomAttributes)
        [StrLen(150)]
        [NotNull()]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Event.Name Get start)

                // *** End programmer edit section *** (Event.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Event.Name Get end)

                // *** End programmer edit section *** (Event.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Event.Name Set start)

                // *** End programmer edit section *** (Event.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Event.Name Set end)

                // *** End programmer edit section *** (Event.Name Set end)
            }
        }
        
        /// <summary>
        /// Place.
        /// </summary>
        // *** Start programmer edit section *** (Event.Place CustomAttributes)

        // *** End programmer edit section *** (Event.Place CustomAttributes)
        [StrLen(150)]
        [NotNull()]
        public virtual string Place
        {
            get
            {
                // *** Start programmer edit section *** (Event.Place Get start)

                // *** End programmer edit section *** (Event.Place Get start)
                string result = this.fPlace;
                // *** Start programmer edit section *** (Event.Place Get end)

                // *** End programmer edit section *** (Event.Place Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Event.Place Set start)

                // *** End programmer edit section *** (Event.Place Set start)
                this.fPlace = value;
                // *** Start programmer edit section *** (Event.Place Set end)

                // *** End programmer edit section *** (Event.Place Set end)
            }
        }
        
        /// <summary>
        /// Type.
        /// </summary>
        // *** Start programmer edit section *** (Event.Type CustomAttributes)

        // *** End programmer edit section *** (Event.Type CustomAttributes)
        [StrLen(150)]
        [NotNull()]
        public virtual string Type
        {
            get
            {
                // *** Start programmer edit section *** (Event.Type Get start)

                // *** End programmer edit section *** (Event.Type Get start)
                string result = this.fType;
                // *** Start programmer edit section *** (Event.Type Get end)

                // *** End programmer edit section *** (Event.Type Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Event.Type Set start)

                // *** End programmer edit section *** (Event.Type Set start)
                this.fType = value;
                // *** Start programmer edit section *** (Event.Type Set end)

                // *** End programmer edit section *** (Event.Type Set end)
            }
        }
        
        
        /// <summary>
        /// StartDate.
        /// </summary>
        // *** Start programmer edit section *** (Event.StartDate CustomAttributes)

        // *** End programmer edit section *** (Event.StartDate CustomAttributes)
        [NotNull()]
        public virtual System.DateTime StartDate
        {
            get
            {
                // *** Start programmer edit section *** (Event.StartDate Get start)

                // *** End programmer edit section *** (Event.StartDate Get start)
                System.DateTime result = this.fStartDate;
                // *** Start programmer edit section *** (Event.StartDate Get end)

                // *** End programmer edit section *** (Event.StartDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Event.StartDate Set start)

                // *** End programmer edit section *** (Event.StartDate Set start)
                this.fStartDate = value;
                // *** Start programmer edit section *** (Event.StartDate Set end)

                // *** End programmer edit section *** (Event.StartDate Set end)
            }
        }
        
        /// <summary>
        /// EndDate.
        /// </summary>
        // *** Start programmer edit section *** (Event.EndDate CustomAttributes)

        // *** End programmer edit section *** (Event.EndDate CustomAttributes)
        [NotNull()]
        public virtual System.DateTime EndDate
        {
            get
            {
                // *** Start programmer edit section *** (Event.EndDate Get start)

                // *** End programmer edit section *** (Event.EndDate Get start)
                System.DateTime result = this.fEndDate;
                // *** Start programmer edit section *** (Event.EndDate Get end)

                // *** End programmer edit section *** (Event.EndDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Event.EndDate Set start)

                // *** End programmer edit section *** (Event.EndDate Set start)
                this.fEndDate = value;
                // *** Start programmer edit section *** (Event.EndDate Set end)

                // *** End programmer edit section *** (Event.EndDate Set end)
            }
        }
        
        /// <summary>
        /// Comment.
        /// </summary>
        // *** Start programmer edit section *** (Event.Comment CustomAttributes)

        // *** End programmer edit section *** (Event.Comment CustomAttributes)
        [NotNull()]
        public virtual string Comment
        {
            get
            {
                // *** Start programmer edit section *** (Event.Comment Get start)

                // *** End programmer edit section *** (Event.Comment Get start)
                string result = this.fComment;
                // *** Start programmer edit section *** (Event.Comment Get end)

                // *** End programmer edit section *** (Event.Comment Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Event.Comment Set start)

                // *** End programmer edit section *** (Event.Comment Set start)
                this.fComment = value;
                // *** Start programmer edit section *** (Event.Comment Set end)

                // *** End programmer edit section *** (Event.Comment Set end)
            }
        }
        
        /// <summary>
        /// Event.
        /// </summary>
        // *** Start programmer edit section *** (Event.Member CustomAttributes)

        // *** End programmer edit section *** (Event.Member CustomAttributes)
        public virtual IIS.calendar.DetailArrayOfMember Member
        {
            get
            {
                // *** Start programmer edit section *** (Event.Member Get start)

                // *** End programmer edit section *** (Event.Member Get start)
                if ((this.fMember == null))
                {
                    this.fMember = new IIS.calendar.DetailArrayOfMember(this);
                }
                IIS.calendar.DetailArrayOfMember result = this.fMember;
                // *** Start programmer edit section *** (Event.Member Get end)

                // *** End programmer edit section *** (Event.Member Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Event.Member Set start)

                // *** End programmer edit section *** (Event.Member Set start)
                this.fMember = value;
                // *** Start programmer edit section *** (Event.Member Set end)

                // *** End programmer edit section *** (Event.Member Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "EventE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EventE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EventE", typeof(IIS.calendar.Event));
                }
            }
            
            /// <summary>
            /// "EventL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EventL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EventL", typeof(IIS.calendar.Event));
                }
            }
        }
    }
}
