//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.calendar
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
using System.Collections.Generic;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Member.
    /// </summary>
    // *** Start programmer edit section *** (Member CustomAttributes)

    // *** End programmer edit section *** (Member CustomAttributes)
    [AutoAltered()]
    [Caption("Участники")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("MemberE", new string[] {
            "ClientDB as \'Участники\'",
            "ClientDB.Name as \'Имя\'"}, Hidden=new string[] {
            "ClientDB.Name"})]
    [MasterViewDefineAttribute("MemberE", "ClientDB", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class Member : ICSSoft.STORMNET.DataObject
    {
        
        public IIS.calendar.ClientDB fClientDB;
        
        private IIS.calendar.Event fEvent;
        
        // *** Start programmer edit section *** (Member CustomMembers)

        // *** End programmer edit section *** (Member CustomMembers)

        
        /// <summary>
        /// Member.
        /// </summary>
        // *** Start programmer edit section *** (Member.ClientDB CustomAttributes)

        // *** End programmer edit section *** (Member.ClientDB CustomAttributes)
        public virtual IIS.calendar.ClientDB ClientDB
        {
            get
            {
                // *** Start programmer edit section *** (Member.ClientDB Get start)

                // *** End programmer edit section *** (Member.ClientDB Get start)
                IIS.calendar.ClientDB result = this.fClientDB;
                // *** Start programmer edit section *** (Member.ClientDB Get end)

                // *** End programmer edit section *** (Member.ClientDB Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Member.ClientDB Set start)

                // *** End programmer edit section *** (Member.ClientDB Set start)
                this.fClientDB = value;
                // *** Start programmer edit section *** (Member.ClientDB Set end)

                // *** End programmer edit section *** (Member.ClientDB Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.calendar.Event.
        /// </summary>
        // *** Start programmer edit section *** (Member.Event CustomAttributes)

        // *** End programmer edit section *** (Member.Event CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.calendar.Event Event
        {
            get
            {
                // *** Start programmer edit section *** (Member.Event Get start)

                // *** End programmer edit section *** (Member.Event Get start)
                IIS.calendar.Event result = this.fEvent;
                // *** Start programmer edit section *** (Member.Event Get end)

                // *** End programmer edit section *** (Member.Event Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Member.Event Set start)

                // *** End programmer edit section *** (Member.Event Set start)
                this.fEvent = value;
                // *** Start programmer edit section *** (Member.Event Set end)

                // *** End programmer edit section *** (Member.Event Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "MemberE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MemberE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MemberE", typeof(IIS.calendar.Member));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Member.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfMember CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfMember CustomAttributes)
    public class DetailArrayOfMember : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.calendar.DetailArrayOfMember members)

        // *** End programmer edit section *** (IIS.calendar.DetailArrayOfMember members)        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Member by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Member.
        /// </summary>
        public DetailArrayOfMember(IIS.calendar.Event fEvent) : 
                base(typeof(Member), ((ICSSoft.STORMNET.DataObject)(fEvent)))
        {
        }
        
        public IIS.calendar.Member this[int index]
        {
            get
            {
                return ((IIS.calendar.Member)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.calendar.Member dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
