<%--flexberryautogenerated="false"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="EventU.aspx.cs" Inherits="IIS.calendar.EventU" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="PageTitlePlaceholder" runat="server">

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AddToHeadPlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div id='calendar'>
        </div>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder0" runat="server">
         <script src="/Scripts/qTip/jquery.qtip.js"  type="text/javascript"></script>
         <script type="text/javascript">
             $(document).ready(function () {
                 $(function () {
                     $('#calendar').fullCalendar({
                         //eventRender: function(event, element) {
                         //    element.qtip({
                         //        content: {
                         //            text: event.title
                         //        }
                                 
                         //    })
                         //},
                         events:'/api/events/',
                         customButtons: {
                             Left:{
                                 text:'Назад',
                                 click: function () {
                                     //var date = new Date($('#calendar').fullCalendar('getDate'));
                                     //var month_int = date.getMonth();
                                     //month_int = month_int - 1;
                                     $('#calendar').fullCalendar('prev');
                                     //postMessage(month_int, '/api/events');
                                     $('#calendar').fullCalendar('addEventSource', '/api/events/');
                                 }
                             },
                             Right: {
                                 text: 'Вперед',
                                 click: function () {
                                     var date = new Date($('#calendar').fullCalendar('getDate'));
                                     var month_int = date.getMonth();
                                     month_int = month_int + 1;
                                     $('#calendar').fullCalendar('next');
                                     $('#calendar').fullCalendar('addEventSource', '/api/events/');
                                 }
                             },
                             myCustomButton: {
                                 text: 'Показать только мои',
                                 click: function() {
                                     $('#calendar').fullCalendar('removeEventSource', '/api/events');
                                     $('#calendar').fullCalendar('addEventSource', '/api/MineEvents');
                                 }
                             }
                         },
                         header: {
                             left: 'Left,Right',
                             center: 'title',
                             right: 'myCustomButton'
                         },
                     })
                 });
             })
 </script>
</asp:Content>
